# -*- coding: utf-8 -*-
"""matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EhflSxBYhRYrYUBi6ROUGqQ9gETYrFPy
"""

import matplotlib.pyplot as plt
x = [1,2,3,4,5]
y = [12,32,22,34,34]
plt.plot(x,y)
plt.show()

months = ["jan","feb","march","april","dec"]
sales = [20000,10000,7000,23444,6544]
plt.plot(months,sales,color = "red", linestyle = "--",linewidth = 2,marker = "." ,label = "2025 sales data")
plt.title("Sales in cloth shop")
plt.xlabel("high selling months")
plt.ylabel("Cloth sales")
plt.legend()
plt.grid()
plt.xticks()
plt.show()

months = ["jan","feb","march","april","dec"]
sales = [20000,10000,7000,23444,6544]
plt.plot(months,sales,color = "blue", linestyle = "--",linewidth = 2,marker = "." ,label = "2025 sales data")
plt.title("Sales in cloth shop")
plt.xlabel("high selling months")
plt.ylabel("Cloth sales")
plt.ylim(10000,20000)
plt.show()